name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        run: rustup update stable && rustup default stable && rustup component add clippy
      - run: cargo check
      - run: cargo clippy -- -D warnings
